/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NothingImport } from './routes/nothing'
import { Route as IndexImport } from './routes/index'
import { Route as NothingAsdImport } from './routes/nothing.asd'

// Create Virtual Routes

const AboutLazyImport = createFileRoute('/about')()

// Create/Update Routes

const AboutLazyRoute = AboutLazyImport.update({
  path: '/about',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/about.lazy').then((d) => d.Route))

const NothingRoute = NothingImport.update({
  path: '/nothing',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NothingAsdRoute = NothingAsdImport.update({
  path: '/asd',
  getParentRoute: () => NothingRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/nothing': {
      id: '/nothing'
      path: '/nothing'
      fullPath: '/nothing'
      preLoaderRoute: typeof NothingImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutLazyImport
      parentRoute: typeof rootRoute
    }
    '/nothing/asd': {
      id: '/nothing/asd'
      path: '/asd'
      fullPath: '/nothing/asd'
      preLoaderRoute: typeof NothingAsdImport
      parentRoute: typeof NothingImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  NothingRoute: NothingRoute.addChildren({ NothingAsdRoute }),
  AboutLazyRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/nothing",
        "/about"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/nothing": {
      "filePath": "nothing.tsx",
      "children": [
        "/nothing/asd"
      ]
    },
    "/about": {
      "filePath": "about.lazy.tsx"
    },
    "/nothing/asd": {
      "filePath": "nothing.asd.tsx",
      "parent": "/nothing"
    }
  }
}
ROUTE_MANIFEST_END */
